# Generated by Django 5.2 on 2025-04-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('specialization', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('password', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=100)),
                ('experience', models.CharField()),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Labtests',
            fields=[
                ('testid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('testdetails', models.TextField()),
            ],
            options={
                'db_table': 'labtests',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offerid', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('validuntil', models.DateField()),
            ],
            options={
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('trackinginfo', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveryoption', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('composition', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('prescriptionneeded', models.BooleanField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phonenumber', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, to='backend.orders')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportid', models.AutoField(primary_key=True, serialize=False)),
                ('filepath', models.TextField()),
                ('testid', models.ForeignKey(db_column='testid', on_delete=django.db.models.deletion.CASCADE, to='backend.labtests')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Supporttickets',
            fields=[
                ('ticketid', models.AutoField(primary_key=True, serialize=False)),
                ('issuetype', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'supporttickets',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionid', models.AutoField(primary_key=True, serialize=False)),
                ('filepath', models.TextField()),
                ('date', models.DateField()),
                ('doctorid', models.ForeignKey(db_column='doctorid', on_delete=django.db.models.deletion.CASCADE, to='backend.doctor')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='backend.users'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationid', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Healthrecords',
            fields=[
                ('recordid', models.AutoField(primary_key=True, serialize=False)),
                ('filepath', models.TextField()),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'healthrecords',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Booksappointment',
            fields=[
                ('appointmentid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('doctorid', models.ForeignKey(db_column='doctorid', on_delete=django.db.models.deletion.CASCADE, to='backend.doctor')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'booksappointment',
            },
        ),
        migrations.CreateModel(
            name='Orderitems',
            fields=[
                ('orderitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, to='backend.orders')),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='backend.product')),
            ],
            options={
                'db_table': 'orderitems',
                'unique_together': {('orderid', 'productid')},
            },
        ),
        migrations.CreateModel(
            name='Useroffers',
            fields=[
                ('useroffersid', models.AutoField(primary_key=True, serialize=False)),
                ('offerid', models.ForeignKey(db_column='offerid', on_delete=django.db.models.deletion.CASCADE, to='backend.offers')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
            options={
                'db_table': 'useroffers',
                'unique_together': {('userid', 'offerid')},
            },
        ),
    ]
